### ISSUE TITLE
Dicionario de Dados

### ISSUE THREAD

**Issue by LucasFerreira1107** [LCarlosA/avanti-bootcamp-cdd#2]
- [x] Realizar coleta inicial de dados, seja ela através de download ou criação de script para download. Você deve criar um arquivo com os dados e coloca-lo na pasta data/raw.

- [x] Criar dicionário de dados, uma estrutura que servirá para explicar o dado.

- Variável: Nome da coluna

- Descrição: Descrição breve da coluna

- tipo: quantitativo ou qualitativo

- subtipo: nominal, ordinal, discreta, contínua.

**Comment by LCarlosA** [comment]
OK!
